apiVersion: v1
kind: Pod 
metadata:
  name: pvc-po 
spec:
  containers:
  - name: busybox
    image: busybox 
    command: ["/bin/sh", "-c", "while true; do sleep 3600; done"]
    volumeMounts:
    - name: pvc-vol
      mountPath: /tmp/pvc-vol
  volumes:
  - name: pvc-vol
    persistentVolumeClaim:
      claimName: pvc
    