apiVersion: v1 
kind: Pod 
metadata:
  name: liveness-po
spec:
  containers:
  - name: busybox
    image: busybox 
    command: ['sh', '-c', 'echo Hello k8s && sleep 3600']
    livenessProbe:
      exec:
        command:
        - echo
        - testing 
      initialDelaySeconds: 5 
      periodSeconds: 5