apiVersion: v1 
kind: Pod 
metadata:
  name: readiness-po
spec:
  containers:
  - name: nginx 
    image: nginx 
    readinessProbe:
      httpGet:
        path: /
        port: 80 
      initialDelaySeconds: 5 
      periodSeconds: 5