apiVersion: v1
kind: Pod 
metadata:
  name: git-sync
spec:
  hostNetwork: True 
  volumes:
  - name: tmp-v 
    emptyDir: {}
  containers:
  - name: nginx 
    image: nginx 
    workingDir: /tmp
    volumeMounts:
    - name: tmp-v 
      mountPath: /tmp
  - name: git-sync 
    image: k8s.gcr.io/git-sync/git-sync:v3.2.0
    volumeMounts:
    - name: tmp-v 
      mountPath: /tmp/git 
    env: 
    - name: GIT_SYNC_REPO
      value: "https://github.com/theJaxon/RHCSA_ENV"
    - name: GIT_SYNC_BRANCH
      value: "master"
    - name: GIT_SYNC_WAIT
      value: "60" 
    - name: GIT_SYNC_WEBHOOK_URL
      value: "http://localhost:9090/-/reload"