apiVersion: v1 
kind: Pod 
metadata:
  name: init-container-2
spec:
  initContainers:
  - name: alpine
    image: alpine 
    args:
    - /bin/sleep
    - "60" # Sleep for 1 minute then initialize the nginx container
  containers:
  - name: nginx 
    image: nginx