apiVersion: v1 
kind: Pod 
metadata:
  name: multi-container-sidecar
spec:
  containers:
  - name: nginx
    image: nginx 
    ports:
    - containerPort: 80 
  - name: busybox
    image: busybox 
    command: ['sh', '-c', 'while true; do sleep 30; done'] 