apiVersion: v1 
kind: Pod 
metadata:
  name: sec-no-access
spec:
  securityContext:
    # Just changed the user and group so that we have access to the file 
    runAsUser: 2000
    fsGroup: 3000
  
  containers:
  - name: busybox
    image: busybox
    command: ['sh', '-c', 'cat /message/message.txt && sleep 7200']
    volumeMounts:
    - name: sec-no-access-vol
      mountPath: /message 

  volumes:
  - name: sec-no-access-vol 
    hostPath:
      path: /etc/message