apiVersion: v1
kind: Pod 
metadata:
  name: test-cm-po-env
spec:
  containers:
    - name: busybox
      image: busybox 
      command: ['sh', '-c', 'echo my name is $(NAME) && sleep 3600']
      env:
      - name: NAME 
        valueFrom:
          configMapKeyRef:
            name: test-cm
            key: NAME
