apiVersion: v1 
kind: Secret 
metadata:
  name: secret
stringData:
  key: passw0rd 

---

apiVersion: v1
kind: Pod 
metadata:
  name: secret-po
spec:
  containers:
  - name: busybox
    image: busybox 
    command: ['sh', '-c', 'echo Hello K8s && sleep 7200']
    env:
    - name: PASSWD 
      valueFrom:
        secretKeyRef:
          name: secret 
          key: key